// @ts-check
import eslint from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import nextPlugin from '@next/eslint-plugin-next';

/**
 * One flat config for the workspace. Type-aware rules are on: AD-13 pins TypeScript at 6.x
 * partly to keep type-aware ESLint working, so running it untyped would waste the constraint.
 *
 * Boundary enforcement is NOT here — dependency-cruiser owns it (.dependency-cruiser.cjs),
 * because DR-1's rule is about module graphs, not syntax.
 *
 * This config is the ONLY lint gate for apps/web: Next 16 removed `next lint`, and AD-9 records
 * the consequence — "CI must invoke ESLint directly or every gate in AD-13's table silently
 * turns off."
 */
/**
 * NFR-26 and the no-user-facing-text rule, shared by every browser-tier package.
 *
 * Hoisted into a constant rather than repeated because ESLint rule options REPLACE rather than
 * merge: a second `no-restricted-syntax` block matching apps/web would silently drop these four
 * entries from it, and a lint rule that stopped matching looks exactly like a lint rule that
 * passes. Spread into each block instead, so adding a browser tier cannot quietly lose them.
 */
const restrictedSyntaxBrowser = [
  {
    selector: 'CallExpression > MemberExpression[property.name="toFixed"]',
    message:
      'NFR-26: no hardcoded format pattern. Declare a named number format in the app\'s ' +
      'i18n/formats.ts and reach it by name.',
  },
  {
    selector:
      'CallExpression > MemberExpression[property.name=/^toLocale(String|DateString|TimeString)$/]',
    message:
      'NFR-26: formatting is derived from the active locale, not chosen at the call site. ' +
      "Use a named format from the app's i18n/formats.ts.",
  },
  {
    selector: 'NewExpression[callee.object.name="Intl"]',
    message:
      'NFR-26: declare the format in the app\'s i18n/formats.ts and reach it by name. A ' +
      'formatter constructed here is a format pattern in a component.',
  },
  {
    selector: 'JSXText[value=/[^\\s]/]',
    message:
      'No user-facing text in code. Every string a person reads is a message key resolved ' +
      'from a catalogue (design_spec.md §13.4); a literal here is invisible to the parity ' +
      'gate and to every translator. Use a message key.',
  },
  // JSXText catches the text BETWEEN tags and nothing else, so a sentence moved into an
  // attribute slipped through — and these are the attributes a screen reader reads aloud,
  // which makes it the accessibility surface (WCAG 2.2 AA) as much as the localization one.
  // Split from `alt` below because the empty string is meaningful there and nowhere else.
  {
    selector:
      "JSXAttribute[name.name=/^(title|placeholder|aria-label|aria-description|aria-placeholder|aria-valuetext|aria-roledescription)$/] > Literal",
    message:
      'No user-facing text in code — an attribute is still text a person reads, and a screen ' +
      'reader announces these. Resolve it from the catalogue: title={t(\'…\')}.',
  },
  {
    // `alt=""` is the correct, required marking for a decorative image, so only a non-empty
    // literal is a violation.
    selector: "JSXAttribute[name.name='alt'] > Literal[value!='']",
    message:
      'No user-facing text in code — alt text is read aloud. Resolve it from the catalogue. ' +
      'An intentionally decorative image keeps alt="".',
  },
];

export default tseslint.config(
  {
    ignores: [
      '**/dist/**', '**/coverage/**', '**/node_modules/**', '**/.next/**',
      // Config files and tooling scripts: CommonJS, and outside any tsconfig project, so
      // type-aware rules cannot parse them. Listed individually rather than blanket-ignoring
      // *.cjs — a source file that ends up unlinted is the failure this rule set exists to
      // prevent.
      'eslint.config.mjs', '.dependency-cruiser.cjs', '**/jest.config.cjs',
      '**/postcss.config.mjs',
      // Delivered design prototypes (design_spec.md §11) — reference artefacts, never built.
      'design/**',
      // Shared agent skills, vendored from elsewhere and not ours to lint.
      '.agents/**',
      // Generated by @tanstack/router-plugin from apps/admin/src/app/routes/ on every build.
      // Committed so `pnpm typecheck` needs no prior build, and kept honest by `routes:check`
      // — but machine output, so not ours to lint.
      '**/route-tree.gen.ts',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      globals: { ...globals.node, ...globals.jest },
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      // Surfaces a forgotten await on a repository call, which under RLS would otherwise
      // present as an empty result rather than an error.
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
    },
  },

  // ── The browser tier: apps/web, apps/admin, packages/ui ─────────────────────────────────
  // Both front ends and the design system. AD-9 makes them two ordinary clients of one API, so
  // the rules that encode project conventions — accessibility, hooks, NFR-26, no user-facing
  // text — apply to both. Framework rules do not; those are the block below.
  {
    files: [
      'apps/web/**/*.{ts,tsx}',
      'apps/admin/**/*.{ts,tsx}',
      'packages/ui/**/*.{ts,tsx}',
    ],
    plugins: {
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // WCAG 2.2 AA is the target on every screen, admin included. design_spec.md §13.4 makes
      // an accessibility review a merge gate for every screen, and UX-108 is cited directly on
      // A-01 — so scoping a11y to the tenant app would exempt the one admin screen that names
      // an accessibility criterion.
      ...jsxA11y.flatConfigs.recommended.rules,
      'no-restricted-syntax': ['error', ...restrictedSyntaxBrowser],
    },
  },

  // ── Next.js only: apps/web ──────────────────────────────────────────────────────────────
  // apps/admin is a Vite SPA (AD-9) and must not inherit any of this. The restricted-syntax
  // list is respread here on purpose — see the constant's comment; omitting the spread would
  // drop NFR-26 from the tenant app.
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      // Pages Router rule. This project is App Router only, so it looks for a `pages/`
      // directory that will never exist and reports its absence on every run.
      '@next/next/no-html-link-for-pages': 'off',

      /**
       * §14.2's `"use cache"` ban is a SECURITY rule, not a performance preference. A cache key
       * the compiler generated without knowing about organization_id would leak a rendered page
       * across tenants ABOVE the RLS boundary of AD-2, where none of its probes would catch it.
       *
       * Next-only because the directive is Next-only. apps/admin holds no tenant data to leak:
       * D-5 gives it no standing access to any organization's report content in the first place.
       */
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ExpressionStatement > Literal[value="use cache"]',
          message:
            'Cache Components are disabled as a security rule (architecture.md §14.2, AD-9). ' +
            'Every page here is tenant-scoped; a compiler-generated cache key does not know ' +
            'about organization_id and would leak across tenants above the RLS boundary.',
        },
        ...restrictedSyntaxBrowser,
      ],

      /**
       * The locale-aware navigation wrappers from src/i18n/navigation.ts are the only ones this
       * app may use. A raw `next/link` renders a working-looking anchor that drops the locale
       * prefix — nothing throws, nothing logs, and the user lands on a redirect that resets
       * their language.
       *
       * apps/admin has no equivalent rule because it has no locale segment to drop: the console
       * is Romanian-only (architecture.md §18), so its router needs no locale-aware wrapper.
       *
       * Scoped to the members that are locale-aware. `notFound`, `useSearchParams` and
       * `useParams` have no locale dimension and stay available.
       */
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'next/link',
              message: "Use `Link` from '@/i18n/navigation' — next/link drops the locale prefix.",
            },
            {
              name: 'next/navigation',
              importNames: ['redirect', 'permanentRedirect', 'usePathname', 'useRouter'],
              message:
                "Use the locale-aware equivalents from '@/i18n/navigation'. notFound, " +
                'useSearchParams and useParams are fine from next/navigation.',
            },
          ],
        },
      ],
    },
  },

  // ── apps/admin only: TanStack Router control flow ───────────────────────────────────────
  {
    files: ['apps/admin/**/*.{ts,tsx}'],
    rules: {
      /**
       * `throw redirect({ to })` is TanStack Router's documented control flow for a route that
       * resolves elsewhere, and `Redirect` is deliberately NOT an Error subclass — the router
       * catches it by identity (`isRedirect`) rather than by type, so making it an Error would
       * mean swallowing real errors that happened to look like one.
       *
       * only-throw-error is therefore correct on the facts and wrong on the intent. The narrow
       * allowance is better than an inline disable: an inline comment would have to be repeated
       * on every route that redirects, and a disable line is invisible to anyone auditing which
       * rules this app actually runs. Everything else still has to throw a real Error.
       *
       * Scoped by declaring package, so an unrelated non-Error throw is still an error here.
       */
      '@typescript-eslint/only-throw-error': [
        'error',
        {
          allow: [
            { from: 'package', package: '@tanstack/router-core', name: 'Redirect' },
          ],
        },
      ],
    },
  },

  // src/i18n/navigation.ts is where the wrappers are created, so it is the one file that must
  // import the module the rule above bans everywhere else.
  {
    files: ['apps/web/src/i18n/navigation.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },
);
