/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as FocusRouteImport } from './routes/_focus';
import { Route as RealmRouteImport } from './routes/_realm';
import { Route as FocusSignInRouteImport } from './routes/_focus/sign-in';
import { Route as RealmAccountsRouteImport } from './routes/_realm/accounts';
import { Route as RealmIdentityProvidersRouteImport } from './routes/_realm/identity-providers';
import { Route as RealmMetricsRouteImport } from './routes/_realm/metrics';
import { Route as RealmNotificationTemplatesRouteImport } from './routes/_realm/notification-templates';
import { Route as RealmOrganizationsRouteImport } from './routes/_realm/organizations';
import { Route as RealmSupportAccessRouteImport } from './routes/_realm/support-access';
import { Route as RealmBillingCollectionsRouteImport } from './routes/_realm/billing/collections';
import { Route as RealmBillingEfacturaRouteImport } from './routes/_realm/billing/efactura';
import { Route as RealmBillingEnterpriseRouteImport } from './routes/_realm/billing/enterprise';
import { Route as RealmBillingInvoicesRouteImport } from './routes/_realm/billing/invoices';
import { Route as RealmBillingPlansRouteImport } from './routes/_realm/billing/plans';
import { Route as RealmBillingRefundsRouteImport } from './routes/_realm/billing/refunds';
import { Route as RealmBillingRevenueRouteImport } from './routes/_realm/billing/revenue';
import { Route as RealmContentIndexRouteImport } from './routes/_realm/content/index';
import { Route as RealmContentPublishRouteImport } from './routes/_realm/content/publish';
import { Route as RealmRulesIndexRouteImport } from './routes/_realm/rules/index';
import { Route as RealmRulesValidationRouteImport } from './routes/_realm/rules/validation';
import { Route as RealmTaxonomyIndexRouteImport } from './routes/_realm/taxonomy/index';
import { Route as RealmTaxonomyMigrationsRouteImport } from './routes/_realm/taxonomy/migrations';
import { Route as RealmBillingReconciliationIndexRouteImport } from './routes/_realm/billing/reconciliation/index';
import { Route as RealmBillingReconciliationExceptionIdRouteImport } from './routes/_realm/billing/reconciliation/$exceptionId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const FocusRoute = FocusRouteImport.update({
  id: '/_focus',
  getParentRoute: () => rootRouteImport,
} as any);
const RealmRoute = RealmRouteImport.update({
  id: '/_realm',
  getParentRoute: () => rootRouteImport,
} as any);
const FocusSignInRoute = FocusSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => FocusRoute,
} as any);
const RealmAccountsRoute = RealmAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => RealmRoute,
} as any);
const RealmIdentityProvidersRoute = RealmIdentityProvidersRouteImport.update({
  id: '/identity-providers',
  path: '/identity-providers',
  getParentRoute: () => RealmRoute,
} as any);
const RealmMetricsRoute = RealmMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => RealmRoute,
} as any);
const RealmNotificationTemplatesRoute =
  RealmNotificationTemplatesRouteImport.update({
    id: '/notification-templates',
    path: '/notification-templates',
    getParentRoute: () => RealmRoute,
  } as any);
const RealmOrganizationsRoute = RealmOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => RealmRoute,
} as any);
const RealmSupportAccessRoute = RealmSupportAccessRouteImport.update({
  id: '/support-access',
  path: '/support-access',
  getParentRoute: () => RealmRoute,
} as any);
const RealmBillingCollectionsRoute = RealmBillingCollectionsRouteImport.update({
  id: '/billing/collections',
  path: '/billing/collections',
  getParentRoute: () => RealmRoute,
} as any);
const RealmBillingEfacturaRoute = RealmBillingEfacturaRouteImport.update({
  id: '/billing/efactura',
  path: '/billing/efactura',
  getParentRoute: () => RealmRoute,
} as any);
const RealmBillingEnterpriseRoute = RealmBillingEnterpriseRouteImport.update({
  id: '/billing/enterprise',
  path: '/billing/enterprise',
  getParentRoute: () => RealmRoute,
} as any);
const RealmBillingInvoicesRoute = RealmBillingInvoicesRouteImport.update({
  id: '/billing/invoices',
  path: '/billing/invoices',
  getParentRoute: () => RealmRoute,
} as any);
const RealmBillingPlansRoute = RealmBillingPlansRouteImport.update({
  id: '/billing/plans',
  path: '/billing/plans',
  getParentRoute: () => RealmRoute,
} as any);
const RealmBillingRefundsRoute = RealmBillingRefundsRouteImport.update({
  id: '/billing/refunds',
  path: '/billing/refunds',
  getParentRoute: () => RealmRoute,
} as any);
const RealmBillingRevenueRoute = RealmBillingRevenueRouteImport.update({
  id: '/billing/revenue',
  path: '/billing/revenue',
  getParentRoute: () => RealmRoute,
} as any);
const RealmContentIndexRoute = RealmContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => RealmRoute,
} as any);
const RealmContentPublishRoute = RealmContentPublishRouteImport.update({
  id: '/content/publish',
  path: '/content/publish',
  getParentRoute: () => RealmRoute,
} as any);
const RealmRulesIndexRoute = RealmRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => RealmRoute,
} as any);
const RealmRulesValidationRoute = RealmRulesValidationRouteImport.update({
  id: '/rules/validation',
  path: '/rules/validation',
  getParentRoute: () => RealmRoute,
} as any);
const RealmTaxonomyIndexRoute = RealmTaxonomyIndexRouteImport.update({
  id: '/taxonomy/',
  path: '/taxonomy/',
  getParentRoute: () => RealmRoute,
} as any);
const RealmTaxonomyMigrationsRoute = RealmTaxonomyMigrationsRouteImport.update({
  id: '/taxonomy/migrations',
  path: '/taxonomy/migrations',
  getParentRoute: () => RealmRoute,
} as any);
const RealmBillingReconciliationIndexRoute =
  RealmBillingReconciliationIndexRouteImport.update({
    id: '/billing/reconciliation/',
    path: '/billing/reconciliation/',
    getParentRoute: () => RealmRoute,
  } as any);
const RealmBillingReconciliationExceptionIdRoute =
  RealmBillingReconciliationExceptionIdRouteImport.update({
    id: '/billing/reconciliation/$exceptionId',
    path: '/billing/reconciliation/$exceptionId',
    getParentRoute: () => RealmRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/sign-in': typeof FocusSignInRoute;
  '/accounts': typeof RealmAccountsRoute;
  '/identity-providers': typeof RealmIdentityProvidersRoute;
  '/metrics': typeof RealmMetricsRoute;
  '/notification-templates': typeof RealmNotificationTemplatesRoute;
  '/organizations': typeof RealmOrganizationsRoute;
  '/support-access': typeof RealmSupportAccessRoute;
  '/billing/collections': typeof RealmBillingCollectionsRoute;
  '/billing/efactura': typeof RealmBillingEfacturaRoute;
  '/billing/enterprise': typeof RealmBillingEnterpriseRoute;
  '/billing/invoices': typeof RealmBillingInvoicesRoute;
  '/billing/plans': typeof RealmBillingPlansRoute;
  '/billing/refunds': typeof RealmBillingRefundsRoute;
  '/billing/revenue': typeof RealmBillingRevenueRoute;
  '/content/publish': typeof RealmContentPublishRoute;
  '/rules/validation': typeof RealmRulesValidationRoute;
  '/taxonomy/migrations': typeof RealmTaxonomyMigrationsRoute;
  '/content/': typeof RealmContentIndexRoute;
  '/rules/': typeof RealmRulesIndexRoute;
  '/taxonomy/': typeof RealmTaxonomyIndexRoute;
  '/billing/reconciliation/$exceptionId': typeof RealmBillingReconciliationExceptionIdRoute;
  '/billing/reconciliation/': typeof RealmBillingReconciliationIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/sign-in': typeof FocusSignInRoute;
  '/accounts': typeof RealmAccountsRoute;
  '/identity-providers': typeof RealmIdentityProvidersRoute;
  '/metrics': typeof RealmMetricsRoute;
  '/notification-templates': typeof RealmNotificationTemplatesRoute;
  '/organizations': typeof RealmOrganizationsRoute;
  '/support-access': typeof RealmSupportAccessRoute;
  '/billing/collections': typeof RealmBillingCollectionsRoute;
  '/billing/efactura': typeof RealmBillingEfacturaRoute;
  '/billing/enterprise': typeof RealmBillingEnterpriseRoute;
  '/billing/invoices': typeof RealmBillingInvoicesRoute;
  '/billing/plans': typeof RealmBillingPlansRoute;
  '/billing/refunds': typeof RealmBillingRefundsRoute;
  '/billing/revenue': typeof RealmBillingRevenueRoute;
  '/content/publish': typeof RealmContentPublishRoute;
  '/rules/validation': typeof RealmRulesValidationRoute;
  '/taxonomy/migrations': typeof RealmTaxonomyMigrationsRoute;
  '/content': typeof RealmContentIndexRoute;
  '/rules': typeof RealmRulesIndexRoute;
  '/taxonomy': typeof RealmTaxonomyIndexRoute;
  '/billing/reconciliation/$exceptionId': typeof RealmBillingReconciliationExceptionIdRoute;
  '/billing/reconciliation': typeof RealmBillingReconciliationIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_focus': typeof FocusRouteWithChildren;
  '/_realm': typeof RealmRouteWithChildren;
  '/_focus/sign-in': typeof FocusSignInRoute;
  '/_realm/accounts': typeof RealmAccountsRoute;
  '/_realm/identity-providers': typeof RealmIdentityProvidersRoute;
  '/_realm/metrics': typeof RealmMetricsRoute;
  '/_realm/notification-templates': typeof RealmNotificationTemplatesRoute;
  '/_realm/organizations': typeof RealmOrganizationsRoute;
  '/_realm/support-access': typeof RealmSupportAccessRoute;
  '/_realm/billing/collections': typeof RealmBillingCollectionsRoute;
  '/_realm/billing/efactura': typeof RealmBillingEfacturaRoute;
  '/_realm/billing/enterprise': typeof RealmBillingEnterpriseRoute;
  '/_realm/billing/invoices': typeof RealmBillingInvoicesRoute;
  '/_realm/billing/plans': typeof RealmBillingPlansRoute;
  '/_realm/billing/refunds': typeof RealmBillingRefundsRoute;
  '/_realm/billing/revenue': typeof RealmBillingRevenueRoute;
  '/_realm/content/publish': typeof RealmContentPublishRoute;
  '/_realm/rules/validation': typeof RealmRulesValidationRoute;
  '/_realm/taxonomy/migrations': typeof RealmTaxonomyMigrationsRoute;
  '/_realm/content/': typeof RealmContentIndexRoute;
  '/_realm/rules/': typeof RealmRulesIndexRoute;
  '/_realm/taxonomy/': typeof RealmTaxonomyIndexRoute;
  '/_realm/billing/reconciliation/$exceptionId': typeof RealmBillingReconciliationExceptionIdRoute;
  '/_realm/billing/reconciliation/': typeof RealmBillingReconciliationIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/sign-in'
    | '/accounts'
    | '/identity-providers'
    | '/metrics'
    | '/notification-templates'
    | '/organizations'
    | '/support-access'
    | '/billing/collections'
    | '/billing/efactura'
    | '/billing/enterprise'
    | '/billing/invoices'
    | '/billing/plans'
    | '/billing/refunds'
    | '/billing/revenue'
    | '/content/publish'
    | '/rules/validation'
    | '/taxonomy/migrations'
    | '/content/'
    | '/rules/'
    | '/taxonomy/'
    | '/billing/reconciliation/$exceptionId'
    | '/billing/reconciliation/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/sign-in'
    | '/accounts'
    | '/identity-providers'
    | '/metrics'
    | '/notification-templates'
    | '/organizations'
    | '/support-access'
    | '/billing/collections'
    | '/billing/efactura'
    | '/billing/enterprise'
    | '/billing/invoices'
    | '/billing/plans'
    | '/billing/refunds'
    | '/billing/revenue'
    | '/content/publish'
    | '/rules/validation'
    | '/taxonomy/migrations'
    | '/content'
    | '/rules'
    | '/taxonomy'
    | '/billing/reconciliation/$exceptionId'
    | '/billing/reconciliation';
  id:
    | '__root__'
    | '/'
    | '/_focus'
    | '/_realm'
    | '/_focus/sign-in'
    | '/_realm/accounts'
    | '/_realm/identity-providers'
    | '/_realm/metrics'
    | '/_realm/notification-templates'
    | '/_realm/organizations'
    | '/_realm/support-access'
    | '/_realm/billing/collections'
    | '/_realm/billing/efactura'
    | '/_realm/billing/enterprise'
    | '/_realm/billing/invoices'
    | '/_realm/billing/plans'
    | '/_realm/billing/refunds'
    | '/_realm/billing/revenue'
    | '/_realm/content/publish'
    | '/_realm/rules/validation'
    | '/_realm/taxonomy/migrations'
    | '/_realm/content/'
    | '/_realm/rules/'
    | '/_realm/taxonomy/'
    | '/_realm/billing/reconciliation/$exceptionId'
    | '/_realm/billing/reconciliation/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FocusRoute: typeof FocusRouteWithChildren;
  RealmRoute: typeof RealmRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_focus': {
      id: '/_focus';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof FocusRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_realm': {
      id: '/_realm';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof RealmRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_focus/sign-in': {
      id: '/_focus/sign-in';
      path: '/sign-in';
      fullPath: '/sign-in';
      preLoaderRoute: typeof FocusSignInRouteImport;
      parentRoute: typeof FocusRoute;
    };
    '/_realm/accounts': {
      id: '/_realm/accounts';
      path: '/accounts';
      fullPath: '/accounts';
      preLoaderRoute: typeof RealmAccountsRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/identity-providers': {
      id: '/_realm/identity-providers';
      path: '/identity-providers';
      fullPath: '/identity-providers';
      preLoaderRoute: typeof RealmIdentityProvidersRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/metrics': {
      id: '/_realm/metrics';
      path: '/metrics';
      fullPath: '/metrics';
      preLoaderRoute: typeof RealmMetricsRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/notification-templates': {
      id: '/_realm/notification-templates';
      path: '/notification-templates';
      fullPath: '/notification-templates';
      preLoaderRoute: typeof RealmNotificationTemplatesRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/organizations': {
      id: '/_realm/organizations';
      path: '/organizations';
      fullPath: '/organizations';
      preLoaderRoute: typeof RealmOrganizationsRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/support-access': {
      id: '/_realm/support-access';
      path: '/support-access';
      fullPath: '/support-access';
      preLoaderRoute: typeof RealmSupportAccessRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/billing/collections': {
      id: '/_realm/billing/collections';
      path: '/billing/collections';
      fullPath: '/billing/collections';
      preLoaderRoute: typeof RealmBillingCollectionsRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/billing/efactura': {
      id: '/_realm/billing/efactura';
      path: '/billing/efactura';
      fullPath: '/billing/efactura';
      preLoaderRoute: typeof RealmBillingEfacturaRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/billing/enterprise': {
      id: '/_realm/billing/enterprise';
      path: '/billing/enterprise';
      fullPath: '/billing/enterprise';
      preLoaderRoute: typeof RealmBillingEnterpriseRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/billing/invoices': {
      id: '/_realm/billing/invoices';
      path: '/billing/invoices';
      fullPath: '/billing/invoices';
      preLoaderRoute: typeof RealmBillingInvoicesRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/billing/plans': {
      id: '/_realm/billing/plans';
      path: '/billing/plans';
      fullPath: '/billing/plans';
      preLoaderRoute: typeof RealmBillingPlansRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/billing/refunds': {
      id: '/_realm/billing/refunds';
      path: '/billing/refunds';
      fullPath: '/billing/refunds';
      preLoaderRoute: typeof RealmBillingRefundsRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/billing/revenue': {
      id: '/_realm/billing/revenue';
      path: '/billing/revenue';
      fullPath: '/billing/revenue';
      preLoaderRoute: typeof RealmBillingRevenueRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/content/': {
      id: '/_realm/content/';
      path: '/content';
      fullPath: '/content/';
      preLoaderRoute: typeof RealmContentIndexRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/content/publish': {
      id: '/_realm/content/publish';
      path: '/content/publish';
      fullPath: '/content/publish';
      preLoaderRoute: typeof RealmContentPublishRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/rules/': {
      id: '/_realm/rules/';
      path: '/rules';
      fullPath: '/rules/';
      preLoaderRoute: typeof RealmRulesIndexRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/rules/validation': {
      id: '/_realm/rules/validation';
      path: '/rules/validation';
      fullPath: '/rules/validation';
      preLoaderRoute: typeof RealmRulesValidationRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/taxonomy/': {
      id: '/_realm/taxonomy/';
      path: '/taxonomy';
      fullPath: '/taxonomy/';
      preLoaderRoute: typeof RealmTaxonomyIndexRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/taxonomy/migrations': {
      id: '/_realm/taxonomy/migrations';
      path: '/taxonomy/migrations';
      fullPath: '/taxonomy/migrations';
      preLoaderRoute: typeof RealmTaxonomyMigrationsRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/billing/reconciliation/': {
      id: '/_realm/billing/reconciliation/';
      path: '/billing/reconciliation';
      fullPath: '/billing/reconciliation/';
      preLoaderRoute: typeof RealmBillingReconciliationIndexRouteImport;
      parentRoute: typeof RealmRoute;
    };
    '/_realm/billing/reconciliation/$exceptionId': {
      id: '/_realm/billing/reconciliation/$exceptionId';
      path: '/billing/reconciliation/$exceptionId';
      fullPath: '/billing/reconciliation/$exceptionId';
      preLoaderRoute: typeof RealmBillingReconciliationExceptionIdRouteImport;
      parentRoute: typeof RealmRoute;
    };
  }
}

interface FocusRouteChildren {
  FocusSignInRoute: typeof FocusSignInRoute;
}

const FocusRouteChildren: FocusRouteChildren = {
  FocusSignInRoute: FocusSignInRoute,
};

const FocusRouteWithChildren = FocusRoute._addFileChildren(FocusRouteChildren);

interface RealmRouteChildren {
  RealmAccountsRoute: typeof RealmAccountsRoute;
  RealmIdentityProvidersRoute: typeof RealmIdentityProvidersRoute;
  RealmMetricsRoute: typeof RealmMetricsRoute;
  RealmNotificationTemplatesRoute: typeof RealmNotificationTemplatesRoute;
  RealmOrganizationsRoute: typeof RealmOrganizationsRoute;
  RealmSupportAccessRoute: typeof RealmSupportAccessRoute;
  RealmBillingCollectionsRoute: typeof RealmBillingCollectionsRoute;
  RealmBillingEfacturaRoute: typeof RealmBillingEfacturaRoute;
  RealmBillingEnterpriseRoute: typeof RealmBillingEnterpriseRoute;
  RealmBillingInvoicesRoute: typeof RealmBillingInvoicesRoute;
  RealmBillingPlansRoute: typeof RealmBillingPlansRoute;
  RealmBillingRefundsRoute: typeof RealmBillingRefundsRoute;
  RealmBillingRevenueRoute: typeof RealmBillingRevenueRoute;
  RealmContentPublishRoute: typeof RealmContentPublishRoute;
  RealmRulesValidationRoute: typeof RealmRulesValidationRoute;
  RealmTaxonomyMigrationsRoute: typeof RealmTaxonomyMigrationsRoute;
  RealmContentIndexRoute: typeof RealmContentIndexRoute;
  RealmRulesIndexRoute: typeof RealmRulesIndexRoute;
  RealmTaxonomyIndexRoute: typeof RealmTaxonomyIndexRoute;
  RealmBillingReconciliationExceptionIdRoute: typeof RealmBillingReconciliationExceptionIdRoute;
  RealmBillingReconciliationIndexRoute: typeof RealmBillingReconciliationIndexRoute;
}

const RealmRouteChildren: RealmRouteChildren = {
  RealmAccountsRoute: RealmAccountsRoute,
  RealmIdentityProvidersRoute: RealmIdentityProvidersRoute,
  RealmMetricsRoute: RealmMetricsRoute,
  RealmNotificationTemplatesRoute: RealmNotificationTemplatesRoute,
  RealmOrganizationsRoute: RealmOrganizationsRoute,
  RealmSupportAccessRoute: RealmSupportAccessRoute,
  RealmBillingCollectionsRoute: RealmBillingCollectionsRoute,
  RealmBillingEfacturaRoute: RealmBillingEfacturaRoute,
  RealmBillingEnterpriseRoute: RealmBillingEnterpriseRoute,
  RealmBillingInvoicesRoute: RealmBillingInvoicesRoute,
  RealmBillingPlansRoute: RealmBillingPlansRoute,
  RealmBillingRefundsRoute: RealmBillingRefundsRoute,
  RealmBillingRevenueRoute: RealmBillingRevenueRoute,
  RealmContentPublishRoute: RealmContentPublishRoute,
  RealmRulesValidationRoute: RealmRulesValidationRoute,
  RealmTaxonomyMigrationsRoute: RealmTaxonomyMigrationsRoute,
  RealmContentIndexRoute: RealmContentIndexRoute,
  RealmRulesIndexRoute: RealmRulesIndexRoute,
  RealmTaxonomyIndexRoute: RealmTaxonomyIndexRoute,
  RealmBillingReconciliationExceptionIdRoute:
    RealmBillingReconciliationExceptionIdRoute,
  RealmBillingReconciliationIndexRoute: RealmBillingReconciliationIndexRoute,
};

const RealmRouteWithChildren = RealmRoute._addFileChildren(RealmRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FocusRoute: FocusRouteWithChildren,
  RealmRoute: RealmRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
