/**
 * The wire contract — NOT to be confused with `apps/api/src/contracts/`.
 *
 *   apps/api/src/contracts/   in-process PORT surface (entitlement.port, notification.port,
 *                             events). Consumed by modules/**. Enforces DR-1.
 *   packages/contracts        this package: the OpenAPI-generated client and shared DTOs.
 *                             Consumed by apps/web and apps/admin. Never by apps/api —
 *                             the API produces it, so importing it would be a cycle.
 *
 * openapi/v1.json is generated by `pnpm --filter @easyesg/api openapi:emit` and committed.
 * `src/generated/v1.ts` is generated from it by `pnpm --filter @easyesg/contracts generate`
 * (openapi-typescript, types only — no runtime). CI regenerates and diffs BOTH in the same
 * gate: a PR that changes a route must commit the regenerated spec and types (P-5, NFR-83).
 *
 * The aliases below are the package's public surface. Consumers import these names rather than
 * indexing `components['schemas'][…]` at every call site — the indexing is the generated file's
 * concern, and keeping it here means a renamed schema breaks one line, not every screen.
 */
import type { components } from './generated/v1';

export type { paths, operations, components } from './generated/v1';
export {
  PROBLEM_CONTENT_TYPE,
  PROBLEM_TYPE,
  type ProblemDocument,
  type ProblemTypeUri,
} from './problem';
export type { Message, ResultList, ResultObject } from './envelope';

// identity — /api/v1/auth (FR-1, FR-3; task 19)
export type RegisterAccountRequest = components['schemas']['RegisterAccountRequestDto'];
export type VerifyEmailRequest = components['schemas']['VerifyEmailRequestDto'];
export type ResendVerificationEmailRequest =
  components['schemas']['ResendVerificationEmailRequestDto'];
export type AccountResponse = components['schemas']['AccountResponseDto'];

// identity — sessions and password reset (FR-4, FR-5, FR-6; task 21)
export type SignInRequest = components['schemas']['SignInRequestDto'];
export type RefreshSessionRequest = components['schemas']['RefreshSessionRequestDto'];
export type SignOutRequest = components['schemas']['SignOutRequestDto'];
export type SessionResponse = components['schemas']['SessionResponseDto'];
export type SessionAccount = components['schemas']['SessionAccountDto'];
export type RequestPasswordResetRequest =
  components['schemas']['RequestPasswordResetRequestDto'];
export type ResetPasswordRequest = components['schemas']['ResetPasswordRequestDto'];
