/**
 * The wire contract — NOT to be confused with `apps/api/src/contracts/`.
 *
 *   apps/api/src/contracts/   in-process PORT surface (entitlement.port, notification.port,
 *                             events). Consumed by modules/**. Enforces DR-1.
 *   packages/contracts        this package: the OpenAPI-generated client and shared DTOs.
 *                             Consumed by apps/web and apps/admin. Never by apps/api —
 *                             the API produces it, so importing it would be a cycle.
 *
 * openapi/v1.json is generated by `pnpm --filter @easyesg/api openapi:emit` and committed.
 * `src/generated/v1.ts` is generated from it by `pnpm --filter @easyesg/contracts generate`
 * (openapi-typescript, types only — no runtime). CI regenerates and diffs BOTH in the same
 * gate: a PR that changes a route must commit the regenerated spec and types (P-5, NFR-83).
 *
 * The aliases below are the package's public surface. Consumers import these names rather than
 * indexing `components['schemas'][…]` at every call site — the indexing is the generated file's
 * concern, and keeping it here means a renamed schema breaks one line, not every screen.
 */
import type { components } from './generated/v1';

export type { paths, operations, components } from './generated/v1';
export {
  PROBLEM_CONTENT_TYPE,
  PROBLEM_TYPE,
  type ProblemDocument,
  type ProblemTypeUri,
} from './problem';
export type { Message, ResultList, ResultObject } from './envelope';
export {
  API_OUTCOME,
  mapOutcome,
  readProblemDocument,
  readResultList,
  readResultObject,
  type ApiFailure,
  type ApiOutcome,
  type ApiOutcomeStatus,
  type ListResult,
} from './outcome';

// identity — /api/v1/auth (FR-1, FR-3; task 19)
export { ACCOUNT_STATUS, isAccountStatus, type AccountStatus } from './account';
export type RegisterAccountRequest = components['schemas']['RegisterAccountRequestDto'];
export type VerifyEmailRequest = components['schemas']['VerifyEmailRequestDto'];
export type ResendVerificationEmailRequest =
  components['schemas']['ResendVerificationEmailRequestDto'];
export type AccountResponse = components['schemas']['AccountResponseDto'];
/** The confirmation's answer since task 155 — the account, and the setup grant for one holding no password. */
export type EmailVerifiedResponse = components['schemas']['EmailVerifiedResponseDto'];

// identity — an account's setup (FR-2, FR-3; task 155, S-36)
export type AccountSetup = components['schemas']['AccountSetupResponseDto'];
export type SetFirstPasswordRequest = components['schemas']['SetFirstPasswordRequestDto'];
export type SetFirstPasswordByGrantRequest =
  components['schemas']['SetFirstPasswordByGrantRequestDto'];
export type SaveSetupProfileRequest = components['schemas']['SaveSetupProfileRequestDto'];

// identity — sessions and password reset (FR-4, FR-5, FR-6; task 21)
export type SignInRequest = components['schemas']['SignInRequestDto'];
export type RefreshSessionRequest = components['schemas']['RefreshSessionRequestDto'];
export type SignOutRequest = components['schemas']['SignOutRequestDto'];
export type SessionResponse = components['schemas']['SessionResponseDto'];
export type SessionAccount = components['schemas']['SessionAccountDto'];
export type RequestPasswordResetRequest =
  components['schemas']['RequestPasswordResetRequestDto'];
export type ResetPasswordRequest = components['schemas']['ResetPasswordRequestDto'];

// identity — the second factor at sign-in (UC-194, UC-195; task 27.3). `POST /auth/session` answers
// one of TWO shapes, discriminated by `kind` — see `SIGN_IN_OUTCOME` in `social.ts`; a client that
// probes for `accessToken` instead has written the discriminator twice.
export type FactorChallengeResponse = components['schemas']['FactorChallengeResponseDto'];
export type CompleteFactorRequest = components['schemas']['CompleteFactorRequestDto'];

// identity — managing the second factor and the linked providers, S-28's reads (UC-11 … UC-12,
// UC-193; tasks 27.2, 27.6). Added 27 Aug 2026: `apps/web` was restating both of these by hand,
// and the copy of `LinkedProviderResponseDto` had widened `provider` from the contract's own
// two-member enum to `string` — which is the drift this package exists to make impossible, and it
// let an unrecognised provider slug reach a rendered sentence.
export type TotpState = components['schemas']['TotpStateResponseDto'];
export type LinkedProvider = components['schemas']['LinkedProviderResponseDto'];

// identity — memberships and members (FR-12, FR-56 … FR-60; tasks 25.2, 25.3). Two shapes and not
// one: `Member` is a person in THIS organization, read with a tenant bound; `AccountMembership` is
// an organization the CALLER belongs to, read before any tenant exists. They never appear together.
export {
  INVITED_ROLE,
  MEMBERSHIP_ROLE,
  MEMBERSHIP_STATUS,
  type InvitedRole,
  type MembershipRole,
  type MembershipStatus,
} from './membership';
export type Member = components['schemas']['MemberResponseDto'];
export type ChangeMemberRoleRequest = components['schemas']['ChangeMemberRoleRequestDto'];
export type AccountMembership = components['schemas']['AccountMembershipResponseDto'];

// identity — S-16's seat region (task 142): the interim ceiling and the seats held against it.
// `allowance` is null where the ceiling cannot be read, which the screen draws as a count it cannot
// show; task 54.2 changes where the number comes from and not this shape.
export type SeatConsumption = components['schemas']['SeatConsumptionResponseDto'];

// identity — invitations (FR-11, FR-57; tasks 26.1, 26.2). Two audiences on one resource, which is
// why the shapes do not overlap: `Invitation` is a row on the administrator's list, read with a
// tenant bound; the preview and acceptance shapes belong to the **bearer** of a link, who may hold
// no session at all. `InvitationTokenRequest` is the body of both bearer routes — the token travels
// in a POST body rather than a URL so it stays out of access logs and referrer headers.
export {
  INVITATION_STANDING,
  MEMBERSHIP_GRANT_KIND,
  type InvitationStanding,
  type MembershipGrantKind,
} from './invitation';
export type Invitation = components['schemas']['InvitationResponseDto'];
export type IssueInvitationRequest = components['schemas']['IssueInvitationRequestDto'];
export type InvitationTokenRequest = components['schemas']['InvitationTokenRequestDto'];
export type InvitationPreview = components['schemas']['InvitationPreviewResponseDto'];
export type AcceptedInvitation = components['schemas']['AcceptedInvitationResponseDto'];

// identity — /api/v1/auth/social (FR-2, FR-4, FR-82; task 24). The OAuth transaction — state,
// nonce, verifier — travels through apps/web's sealed transaction cookie, never readable in the
// browser; these shapes are the back-channel surface between the web tier and the api.
export {
  SOCIAL_PROVIDER,
  SIGN_IN_OUTCOME,
  SOCIAL_SIGN_IN_INTENT,
  isSocialProvider,
  isSocialSignInIntent,
  socialCallbackPath,
  type SocialProvider,
  type SocialSignInIntent,
} from './social';
export type SocialChallengeRequest = components['schemas']['SocialChallengeRequestDto'];
export type SocialChallengeResponse = components['schemas']['SocialChallengeResponseDto'];
export type CompleteSocialSignInRequest =
  components['schemas']['CompleteSocialSignInRequestDto'];
export type SocialProvidersResponse = components['schemas']['SocialProvidersResponseDto'];

// core — the organization (FR-13 … FR-16; task 29). `Organization` is the whole profile; S-04
// creates it with four of those fields and S-15 fills in the rest, so the create request is its
// own shape rather than a `Partial<Organization>` — the fields a founding screen may set are a
// decision (UC-49), not the ones that happen to be nullable.
//
// `CountryLegalForms` answers both screens in one read: S-04 builds its country field from the
// entries, S-15 its legal-form field from the matching one. Every value is a KEY resolved through
// the message catalogue (OQ-43) — a form or a country rendered raw is an internal identifier on a
// screen, which CLAUDE.md's user-facing-text rule forbids in terms.
export type Organization = components['schemas']['OrganizationResponseDto'];
export type CreateOrganizationRequest = components['schemas']['CreateOrganizationRequestDto'];
// The switch's body (task 83.1), read since task 83.3 by S-37's choice.
export type SwitchActiveOrganizationRequest =
  components['schemas']['SwitchActiveOrganizationRequestDto'];
export type UpdateOrganizationRequest =
  components['schemas']['UpdateOrganizationProfileRequestDto'];
export type CountryLegalForms = components['schemas']['CountryLegalFormsResponseDto'];
/** One activity code the S-13 picker offers — the key stored and the words it was chosen by
 *  (FR-17, task 30.4.1). Searched server-side: the classifier is 996 entries in three languages. */
export type NaceCodeMatch = components['schemas']['NaceCodeResponseDto'];

// core — reporting entities (FR-17 … FR-20; tasks 29.3, 29.4). `sites` and `consolidationMembers`
// are **whole-collection** saves on both writes: a member with an id is edited, one without is
// added, and a stored member the array omits is removed. That is the API's own semantics and the
// reason S-13's Record holds the two lists in its form rather than issuing per-row writes.
export type ReportingEntity = components['schemas']['ReportingEntityResponseDto'];
export type CreateReportingEntityRequest =
  components['schemas']['CreateReportingEntityRequestDto'];
export type UpdateReportingEntityRequest =
  components['schemas']['UpdateReportingEntityRequestDto'];
export type EntitySite = components['schemas']['SiteResponseDto'];
export type ConsolidationMember = components['schemas']['ConsolidationMemberResponseDto'];
// core — reporting periods (FR-21, FR-22, FR-45, FR-66; tasks 31.1, 31.2, consumed by S-14).
//
// **Every boundary is a `LegalDate`, never an instant** (NFR-34). `2026-12-31` is the case the
// distinction was drawn for: as an epoch value it falls in the wrong fiscal year for a reader in
// another zone, and FR-125 makes a document filed against the wrong year uncorrectable by editing.
// The pairing is an object rather than two sibling fields so the zone cannot be half-supplied.
export type LegalDate = components['schemas']['LegalDateDto'];
/**
 * The wizard's surface (task 89; S-07). Aliased here for the same reason every other DTO is: the
 * generated names carry `Dto` and the schema's own shape, and a screen should read the product's
 * vocabulary rather than the emitter's.
 */
export {
  COLUMN_OF_KIND,
  COMPARABILITY,
  DISCLOSURE_KIND,
  DISCLOSURE_ORIGIN,
  DISCLOSURE_STATE,
  MEMBER_SEPARATOR,
  REPORT_STATUS,
  VALUE_COLUMN,
  membersOf,
  type Comparability,
  type DisclosureKind,
  type DisclosureOrigin,
  type DisclosureState,
  type ReportStatus,
  type ValueColumn,
} from './disclosure';
/** The report record (task 31.3) — its status is what tells S-07 a locked period has made it read-only (UX-13). */
export type Report = components['schemas']['ReportResponseDto'];
/** Creating one (UC-18; task 32.3). Carries the period and an optional scope — the two version pins
 *  are copied from the period and are deliberately not fields (FR-66, DR-4). */
export type CreateReportRequest = components['schemas']['CreateReportRequestDto'];
/** UC-175's reminder about a report, sent from S-16 (task 50.3). */
export type SendReportReminderRequest = components['schemas']['SendReportReminderRequestDto'];
export type DisclosureModuleSummary = components['schemas']['DisclosureModuleSummaryDto'];
export type DisclosureField = components['schemas']['DisclosureFieldDto'];
/** One answer a choice field offers (task 91.1): `value` is the member's taxonomy-qualified name, what an answer stores. */
export type DisclosureOption = components['schemas']['DisclosureOptionDto'];
/** What a field would hold if the reporter accepted what the platform already knows (task 91.2; FR-27). Committed by the client, never by the read. */
export type DisclosureDefault = components['schemas']['DisclosureDefaultDto'];
export type DisclosureStep = components['schemas']['DisclosureStepDto'];
/**
 * One classification axis and the members a reporter may add a row from (task 36.5; UC-22).
 *
 * On the **step**, not the field: every element on an axis shares one domain, so B4's three
 * emissions would otherwise carry 94 pollutants three times over and B7's would carry 973.
 */
export type DisclosureAxis = components['schemas']['DisclosureAxisDto'];
export type DisclosureValueWrite = components['schemas']['DisclosureValueWriteDto'];
export type WriteDisclosureValuesRequest =
  components['schemas']['WriteDisclosureValuesRequestDto'];
export type DisclosureValueResponse = components['schemas']['DisclosureValueResponseDto'];
/**
 * One value a derived figure is computed from (task 36.10; UC-26, UC-27).
 *
 * **Not a disclosure**, which is why it is a type of its own rather than a variant: it carries no
 * state, unit, dimension or applicability, and EFRAG words it in the Digital Template rather than in
 * the taxonomy — so the browser names it from its own catalogue and the api serves only the key.
 */
export type DerivationInput = components['schemas']['DerivationInputDto'];
export type DerivationInputWrite = components['schemas']['DerivationInputWriteDto'];
export type WriteDerivationInputsRequest =
  components['schemas']['WriteDerivationInputsRequestDto'];
/** The prior-period comparative (task 34.3; UC-45, FR-46). */
export type PriorPeriodComparatives = components['schemas']['PriorPeriodResponseDto'];

export type ReportingPeriod = components['schemas']['ReportingPeriodResponseDto'];
/**
 * The report opened against a period, or `null` where none has been (task 32.4).
 *
 * `null` is the state FR-23's overview exists to show: a report is an explicit creation, so a
 * period with a due date and nobody working on it is a row rather than an absence.
 */
export type PeriodReport = components['schemas']['PeriodReportDto'];
export type OpenReportingPeriodRequest =
  components['schemas']['OpenReportingPeriodRequestDto'];
export type UpdateReportingPeriodRequest =
  components['schemas']['UpdateReportingPeriodRequestDto'];
/** UC-58's stated reason. Required, and required to say something — UX-72 displays it thereafter. */
export type ReopenPeriodRequest = components['schemas']['ReopenPeriodRequestDto'];
export type PeriodReopening = components['schemas']['PeriodReopeningResponseDto'];

/** FR-15's attribution line on S-15 — who last changed the profile, and when (task 30.3). */
export type OrganizationChangeAttribution =
  components['schemas']['OrganizationChangeAttributionDto'];

// platform — /api/v1/auth/admin (FR-75; task 23, the two-step handshake since 24 Aug 2026).
// The challenge and the session travel as sealed httpOnly cookies the api sets — these shapes
// are the BODY surface only; tokens and the challenge deliberately absent.
export type AdminChallengeRequest = components['schemas']['AdminChallengeRequestDto'];
export type AdminChallengeResponse = components['schemas']['AdminChallengeResponseDto'];
export type AdminFactorRequest = components['schemas']['AdminFactorRequestDto'];
export type AdminSessionResponse = components['schemas']['AdminSessionResponseDto'];
export type AdminAccount = components['schemas']['AdminAccountDto'];
export {
  ADMIN_ROLE,
  ADMIN_ROSTER_KIND,
  ADMIN_STANDING,
  IDENTITY_PROVIDER_ENABLEMENT_BLOCKER,
  SYSTEM_AUDIT_ACTION,
  type AdminRole,
  type AdminRosterKind,
  type AdminStanding,
  type IdentityProviderEnablementBlocker,
  type SystemAuditAction,
} from './admin';
/** One organization in A-02's register (task 67.3) — account-level metadata, never report content. */
export type OrganizationRegisterRow = components['schemas']['OrganizationRegisterRowResponseDto'];
/** Task 167 — a person in an organization, as A-02's record lists them: whether they gave a phone, never the number. */
export type OrganizationMember = components['schemas']['OrganizationMemberResponseDto'];
/** Task 167 — one member's phone, disclosed to one operator and recorded in the system audit log. */
export type DisclosedPhone = components['schemas']['DisclosedPhoneResponseDto'];

// platform — A-08's accounts, invitations and log, and A-20's acceptance (FR-80, FR-81; task 67.4).
/** One row of A-08's account table: an account in either realm, or a pending invitation. */
export type AdminRosterRow = components['schemas']['AdminRosterRowResponseDto'];
export type InviteAdministratorRequest = components['schemas']['InviteAdministratorRequestDto'];
/** An invitation just sent — never its link, which exists only in the email. */
export type AdminInvitation = components['schemas']['AdminInvitationResponseDto'];
export type AdminInvitationTokenRequest = components['schemas']['AdminInvitationTokenRequestDto'];
export type AdminInvitationPreview = components['schemas']['AdminInvitationPreviewResponseDto'];
export type AdminEnrolment = components['schemas']['AdminEnrolmentResponseDto'];
export type AcceptAdminInvitationRequest = components['schemas']['AcceptAdminInvitationRequestDto'];
export type AcceptedAdminInvitation = components['schemas']['AcceptedAdminInvitationResponseDto'];
/** One entry of A-08's system audit log — parties flattened into id and address. */
export type SystemAuditLogEntry = components['schemas']['SystemAuditLogEntryResponseDto'];

// platform — A-19's operator credentials and A-01's recovery sign-in (FR-80, UC-212; task 144).
/** What A-19 reads: when the recovery codes were issued and how many remain — never a code. */
export type AdminCredentials = components['schemas']['AdminCredentialsResponseDto'];
export type ChangeAdminPasswordRequest = components['schemas']['ChangeAdminPasswordRequestDto'];
export type AdminPasswordChanged = components['schemas']['AdminPasswordChangedResponseDto'];
/** The current password, which every A-19 write asks for. */
export type AdminReauthenticationRequest = components['schemas']['AdminReauthenticationRequestDto'];
export type ConfirmAdminReenrolmentRequest = components['schemas']['ConfirmAdminReenrolmentRequestDto'];
/** A new set of ten recovery codes — the only response that ever carries them. */
export type AdminRecoveryCodes = components['schemas']['AdminRecoveryCodesResponseDto'];
export type AdminRecoveryRequest = components['schemas']['AdminRecoveryRequestDto'];
/** A recovery sign-in's session, with how many codes remain. */
export type AdminRecoveredSession = components['schemas']['AdminRecoveredSessionResponseDto'];

// platform — support access by the organization's consent: A-07's requests, grants and log, and the tenant
// banner that answers them (FR-77 … FR-79, UC-85, UC-86; task 67.9).
export {
  SUPPORT_ACCESS_ACTOR_REALM,
  SUPPORT_ACCESS_DECISION,
  SUPPORT_ACCESS_READ_PURPOSE,
  SUPPORT_ACCESS_STATE,
  type SupportAccessActorRealm,
  type SupportAccessDecisionKind,
  type SupportAccessReadPurpose,
  type SupportAccessState,
} from './support-access';
/** A request as it stands — what the banner shows, and the part of A-07's log entry every reader shares. */
export type SupportAccessRequest = components['schemas']['SupportAccessRequestResponseDto'];
/** The banner's whole read: requests awaiting an answer (an administrator's only), and access running now. */
export type OrganizationSupportAccess = components['schemas']['OrganizationSupportAccessResponseDto'];
export type RaiseSupportAccessRequest = components['schemas']['RaiseSupportAccessRequestDto'];
/** A request just raised — waiting for the organization. */
export type SupportAccessRaised = components['schemas']['SupportAccessRaisedResponseDto'];
/** One entry of A-07's log: the request, who decided, how it ended, and every read made under it. */
export type SupportAccessLogEntry = components['schemas']['SupportAccessLogEntryResponseDto'];
export type SupportAccessDecision = components['schemas']['SupportAccessDecisionResponseDto'];
export type SupportAccessAccess = components['schemas']['SupportAccessAccessResponseDto'];

// platform — A-18's social identity providers: the configuration in force, and the three writes that each publish a
// new revision of it (FR-82, UC-70; task 67.11).
/** One provider as A-18 shows it — its configuration in force, whether the server holds its secret and where, and who has linked it. */
export type IdentityProvider = components['schemas']['IdentityProviderResponseDto'];
export type ConfigureIdentityProviderRequest = components['schemas']['ConfigureIdentityProviderRequestDto'];
/** The revision an enablement or a disablement was made against. */
export type IdentityProviderRevisionRequest = components['schemas']['IdentityProviderRevisionRequestDto'];
/** The configuration revision a write just put in force. */
export type IdentityProviderPublication = components['schemas']['IdentityProviderPublicationResponseDto'];

// platform — A-17's notification categories: each category's behaviour in force, its switch-offs and its wording, the
// preview that discloses what a change does for recipients, and the two writes that each publish a revision (FR-173,
// UC-176; task 67.10).
export {
  CATEGORY_CONSEQUENCE,
  NOTIFICATION_CATEGORY,
  NOTIFICATION_CHANNEL,
  NOTIFICATION_CLASSIFICATION,
  isNotificationCategoryKey,
  type CategoryConsequenceKind,
  type NotificationCategoryKey,
  type NotificationChannel,
  type NotificationClassification,
} from './notification';
/** One category as A-17 shows it — what code declares, the behaviour in force and who published it, and its words. */
export type ConsoleCategory = components['schemas']['ConsoleCategoryResponseDto'];
export type CategoryWording = components['schemas']['CategoryWordingResponseDto'];
export type CategoryBehaviourRequest = components['schemas']['CategoryBehaviourRequestDto'];
export type CategoryPublicationRequest = components['schemas']['CategoryPublicationRequestDto'];
export type CategoryReversionRequest = components['schemas']['CategoryReversionRequestDto'];
/** What a publication would change for recipients, one entry per consequence. */
export type CategoryPreview = components['schemas']['CategoryPreviewResponseDto'];
export type CategoryConsequence = components['schemas']['CategoryConsequenceResponseDto'];
/** The configuration revision a publication or a revert just put in force. */
export type CategoryPublication = components['schemas']['CategoryPublicationResponseDto'];

// platform — AD-15's socket handshake (task 147): a single-use, thirty-second ticket, minted through the pass-through
// and presented as the socket upgrade's `ticket` query parameter.
export type SocketTicket = components['schemas']['SocketTicketResponseDto'];

// platform — AD-15's event catalogue (task 146): each event a pushed hint may name, its audience, and the readable path
// that is its authority; `pnpm events:check` holds it to the contract. Since task 149 the names as a vocabulary, and
// the socket's address and close codes as the browser's client meets them.
export {
  EVENT_CATALOGUE,
  EVENT_NAME,
  EVENT_ROUTING_KEY,
  isEventName,
  type EventCatalogueEntry,
  type EventFrame,
  type EventName,
  type EventRoutingKey,
  type ReadablePath,
} from './events/catalogue';
export { SOCKET_CLOSE, SOCKET_PATH, SOCKET_TICKET_PARAMETER, type SocketCloseCode } from './events/socket';

// platform — S-26's notification centre (FR-161, FR-162; tasks 50.1.2, 50.2.1). The words arrive resolved in the
// request's language, each absent where none is written; the category key is for the client to act on, never to show.
/** One notice in the recipient's centre, with this recipient's read state. */
export type NotificationItem = components['schemas']['NotificationItemResponseDto'];

// platform — FR-169's one-click unsubscribe (task 52.2.2): S-38's read and its switch, both public and both taking the
// signed token in a POST body. The standing is the one vocabulary a screen branches on.
export { UNSUBSCRIBE_STANDING, type UnsubscribeStanding } from './notification';
export type UnsubscribeTokenRequest = components['schemas']['UnsubscribeTokenRequestDto'];
export type UnsubscribeAnswer = components['schemas']['UnsubscribeResponseDto'];
export type UnreadCount = components['schemas']['UnreadCountResponseDto'];

// identity — S-27's profile (FR-9, FR-10, FR-52, FR-169; task 52.3): the name as two parts and as every surface shows
// it, the sign-in address, the optional job title and phone, and three languages chosen independently.
export type AccountProfile = components['schemas']['AccountProfileResponseDto'];
export type SaveAccountProfileRequest = components['schemas']['SaveAccountProfileRequestDto'];

// platform — S-27's notification preferences (FR-163; task 52.1): every category the account can receive, each on the
// channels it travels on, and the write that replaces the set switched off.
export type NotificationPreferences = components['schemas']['NotificationPreferencesResponseDto'];
export type CategoryPreferences = components['schemas']['CategoryPreferencesResponseDto'];
export type SetNotificationPreferencesRequest = components['schemas']['SetNotificationPreferencesRequestDto'];
