/**
 * The wire contract — NOT to be confused with `apps/api/src/contracts/`.
 *
 *   apps/api/src/contracts/   in-process PORT surface (entitlement.port, notification.port,
 *                             events). Consumed by modules/**. Enforces DR-1.
 *   packages/contracts        this package: the OpenAPI-generated client and shared DTOs.
 *                             Consumed by apps/web and apps/admin. Never by apps/api —
 *                             the API produces it, so importing it would be a cycle.
 *
 * openapi/v1.json is generated by `pnpm --filter @easyesg/api openapi:emit` and committed.
 * CI regenerates and diffs it: a PR that changes a route must commit the regenerated spec
 * (P-5, NFR-83).
 */
export {};
