#!/usr/bin/env bash
# Removes every build output, leaving node_modules and .env files alone.
#
# WHY THIS EXISTS. Task 17's pipeline went red on a gate that had passed locally every time:
# `test:e2e` needed `packages/i18n/dist`, which only `test` built, and on a developer's machine that
# directory is always already there from some earlier command. On a fresh checkout it is not.
#
# The general shape is worth naming, because it will recur: **a gate must not depend on state a
# previous command left behind.** That dependency is invisible on an incrementally-built tree and
# obvious on a clean one, so `pnpm gates:clean` is the only local run that can see it.
#
# It deliberately does NOT use `git clean -xd`, which would also delete `.env` files and
# `node_modules` — the first breaks the stack, the second turns a two-minute check into a
# reinstall nobody will wait for.
set -euo pipefail
cd "$(dirname "$0")/.."

# Compiled output and framework caches. `next-env.d.ts` is regenerated by `next build` and its
# absence is already known to be harmless (checked when the workflow was written).
rm -rf apps/*/dist apps/*/.next apps/*/coverage packages/*/dist coverage

# Incremental-compile state. Left behind, it makes tsc believe it already emitted files that a
# `deleteOutDir` build has since removed — a build that "succeeds" into an empty directory.
find . -name '*.tsbuildinfo' -not -path './node_modules/*' -not -path '*/node_modules/*' -delete

echo "clean: build outputs removed; node_modules and .env kept."
